### PR TITLE
Fixed a small typo in MockSlingHttpServletResponse.getStatusMessage()…

### PR DESCRIPTION
**Pull request by rmcdouga**
… (was geStatusMessage).

### CODE REVIEW

**Comment by rmcdouga** [comment]
Normally, I create an issue and get permission before creating a pull request, but this one seems like a no brainer.  There appears to be a typo in getStatusMessage(), so I've just created a pull request to correct it.

**Comment by rombert** [comment]
@rmcdouga - this is indeed just a typo. However, since this is API, the baseline check now fails

```
[INFO]   PACKAGE_NAME                                       DELTA      CUR_VER    BASE_VER   REC_VER    WARNINGS  
[INFO] = ================================================== ========== ========== ========== ========== ==========
[INFO] * org.apache.sling.servlethelpers                    major      1.5.0      1.5.0      2.0.0      Version increase required
[INFO]      > class org.apache.sling.servlethelpers.MockSlingHttpServletResponse
[INFO]          - method geStatusMessage()
[INFO]              - return java.lang.String
[INFO]          + method getStatusMessage()
[INFO]              + return java.lang.String
```

I'll let

**Comment by stefanseifert** [comment]
thanks for bringing this up.
to avoid breaking the compatibility with previous version we should keep but deprecated the old method `geStatusMessage`, and add the new, correct method `getStatusMessage`. geStatusMessage  class getStatusMessage internally.

**Comment by rmcdouga** [comment]
Sorry, that last amendment (2d06796) was not meant to go into the same pull request.  I was working on a different PR that I will potentially submit later after opening up an issue.

I will back out the last change and then update the original change by adding back in the old method with deprecation.

I'm not sure if I will get around to it today, but I am hoping to have that done by Monday...

**Comment by rmcdouga** [comment]
OK, I have created a second pull request (#5 ) and am closing this pull request.  Sorry for the inconvenience, I am new to Git and am still "getting my sea legs".

**Pull request closed without merging**
